[theme]
base="dark"
primaryColor="#0080ff"
backgroundColor="#0a0e17"
secondaryBackgroundColor="#131b2e"
textColor="#f8fafc"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
